version: "3.8"

services:
  apihealthmonitoring:
    image: mmercan/healthcheck-apihealthmonitoring:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../../
      dockerfile: Apis/Sentinel.Api.HealthMonitoring/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
