FROM mmercan/sonarqube-dotnet60-sdk:latest AS test
ARG buildtime_APPID
ARG buildtime_APPSECRET
ARG buildtime_ADID
ARG buildtime_SONARKEY
ARG buildtime_RabbitMQConnection
ARG buildtime_RedisConnection
# ENV DOTNET_USE_POLLING_FILE_WATCHER=1
# ENV ASPNETCORE_ENVIRONMENT=Development
# ENV SONAR_HOST http://sonar.myrcan.com
# RUN apt-get update && apt-get install -y openjdk-8-jdk
# RUN dotnet tool install --global dotnet-sonarscanner
# ENV PATH="${PATH}:/root/.dotnet/tools"
ENV ASPNETCORE_URLS=http://+:80
ENV PROJECT=Sentinel.Health.k8
ENV VERSION=1.0
ENV SONARKEY=$buildtime_SONARKEY
ENV AzureAd__ClientId=$buildtime_APPID
ENV AzureAd__Secret=$buildtime_APPSECRET
ENV AzureAd__TenantId=$buildtime_ADID
ENV RabbitMQConnection=$buildtime_RabbitMQConnection
ENV RedisConnection=$buildtime_RedisConnection
ENV SONAR_HOST=https://sonarcloud.io



WORKDIR /src
COPY . .

RUN ["chmod", "+x", "./docker-sonar-tests-entrypoint.sh"]
ENTRYPOINT ["./docker-sonar-tests-entrypoint.sh"]