version: "3.4"

services:
  sentinel-healthcheck-test:
    image: sentinel-healthcheck-test
    build:
      target: test
      context: .
      dockerfile: dockerfile-sonar
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
