version: "3.8"

services:
  sentinel-healtchecker:
    image: mmercan/healthcheck-testapp:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../../
      dockerfile: TestCases/BaseApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
