{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "sentinel-worker-sync.fullname" . }}-secret"
  labels:
    {{- include "sentinel-worker-sync.labels" . | nindent 4 }}
type: "Opaque"
data:
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}

{{- end }}
