apiVersion: v1
kind: Secret
metadata:
  name: azuredns-config
  labels:
    {{- include "wildcard-cert-cluster-issuer.labels" . | nindent 4 }}
type: "Opaque"
data:
 client-secret: {{ default "" .Values.AzureClientSecret | b64enc | quote }}
