version: "3.8"

services:
  sentinel-secretgenerator:
    image: mmercan/healthcheck-secretgenerator:${TAGVersion}-prod-linux
    build:
      target: final
      context: ../../
      dockerfile: Workers/Sentinel.Worker.SecretGenerator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
