{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sentinel-tester-testapp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := printf "%s.%s.%s" "testapp" .Values.environment .Values.hostdomain -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "sentinel-tester-testapp.name" . }}
    helm.sh/chart: {{ include "sentinel-tester-testapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: myrcan-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "sentinel-tester-testapp.fullname" . }}
            port: 
              number: 80
  tls:
  - hosts:
    - {{ $host }}
    secretName: health-wildcard-tls
{{- end }}
