{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sentinel-tester-testapp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := printf "%s.%s.%s" "testapp" .Values.environment .Values.hostdomain -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "sentinel-tester-testapp.name" . }}
    helm.sh/chart: {{ include "sentinel-tester-testapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ $host }}
    secretName:  {{ $host }}-secret
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "sentinel-tester-testapp.fullname" . }}
          servicePort: 80
{{- end }}
