apiVersion: "sentinel.mercan.io/v1"
kind: HealthCheck
metadata:
  name: turquoise-sync-dev-turquoise-worker-sync-healthcheck
spec:
  service: "turquoise-sync-dev-turquoise-worker-sync"
  crontab: "*/2 * * * *"
  cert: ""
