{{- $name := include "healthcheck-rabbitmq.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthcheck-rabbitmq.fullname" . }}
  labels:
    {{- include "healthcheck-rabbitmq.labels" . | nindent 4 }}
  annotations:
    {{- include "healthcheck-rabbitmq.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "healthcheck-rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "healthcheck-rabbitmq.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Thealthcheck-rabbitmq.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "healthcheck-rabbitmq.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
          - mountPath: /etc/rabbitmq
            name: config
      volumes:
        - name: config
          configMap:
            name: {{$cfgname}}
            items:
            - key: rabbitmq-config
              path: rabbitmq.conf
