{{- if .Values.istio.enabled -}}
{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "healthcheck-rabbitmq.fullname" . }}-vs
spec:
  hosts:
    - {{ $host }}
  gateways:
    - {{ include "healthcheck-rabbitmq.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "healthcheck-rabbitmq.fullname" . }}-http  # Service Name
            subset: v1
            port:
              number: 80

{{- end }}