{{- $name := include "healthcheck-rabbitmq.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "healthcheck-rabbitmq.name" . }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "healthcheck-rabbitmq.labels" . | nindent 4 }}
  annotations:
    {{- include "healthcheck-rabbitmq.annotations" . | nindent 4 }}
type: "Opaque"
data:
 RabbitMQConnection:  {{ printf "host=%s;username=%s;password=%s" $name .Values.rabbitmq.username .Values.rabbitmq.password | b64enc | quote }}
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}