apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthcheck-rabbitmq.fullname" . }}-http
  labels:
    {{- include "healthcheck-rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http               
    port: 80               
    targetPort: 15672
    protocol: TCP    
  selector:
    {{- include "healthcheck-rabbitmq.selectorLabels" . | nindent 4 }}

