apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-domain
spec:
  secretName: wildcard-tls
  dnsNames:
    - '*.myrcan.com' 
  commonName: '*.myrcan.com'
  issuerRef:
    name: myrcan-issuer
    kind: ClusterIssuer
    group: cert-manager.io

