apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-domain
spec:
  secretName: wildcard-domain-tls-secret
  dnsNames:
    - '*.myrcan.com' 
  commonName: '*.myrcan.com'
  issuerRef:
    name: myrcan-issuer
    kind: Issuer
    group: cert-manager.io
  acme:
    config:
    - dns01:
        provider: azure-dns
        ingressClass: nginx
      domains:
      - '*.myrcan.com'
