{{- if .Values.istio.enabled -}}
{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "healthcheck-mongodb.name" . }}-vs
spec:
  hosts:
    - {{ include "healthcheck-mongodb.name" . }}
  gateways:
    - {{ include "healthcheck-mongodb.name" . }}-gateway
  tcp:
    - match:
      - port: 27017
      route:
      - destination:
          host: {{ include "healthcheck-mongodb.name" . }}  # Service Name
          port:
            number: 27017
{{- end }}