{{- $name := include "healthcheck-mongodb.name" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "healthcheck-mongodb.fullname" . }}-secret"
  labels:
    app.kubernetes.io/name: {{ include "healthcheck-mongodb.name" . }}
    helm.sh/chart: {{ include "healthcheck-mongodb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: "Opaque"
data:
 Mongodb__ConnectionString:  {{ printf "mongodb://%s:%s@%s:27017/admin?readPreference=primary" .Values.secrets.MONGO_INITDB_ROOT_USERNAME .Values.secrets.MONGO_INITDB_ROOT_PASSWORD $name | b64enc | quote }}
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}