apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthcheck-mongodb.name" . }}
  labels:
    {{- include "healthcheck-mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "healthcheck-mongodb.selectorLabels" . | nindent 4 }}
