apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-mailhog.fullname" . }}
  labels:
    {{- include "sentinel-mailhog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP      
    - name: transport          
      port: 1025               
      targetPort: 1025
      protocol: TCP
  selector:
    {{- include "sentinel-mailhog.selectorLabels" . | nindent 4 }}
