{{- $name := include "healthcheck-redis.name" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "healthcheck-redis.name" . }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "healthcheck-redis.name" . }}
    helm.sh/chart: {{ include "healthcheck-redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: "Opaque"
data:
 RedisConnection:  {{ printf "%s:6379,defaultDatabase=1,password=%s,connectTimeout=1000,abortConnect=false" $name .Values.password | b64enc | quote }}
 RedisExternalConnection:  {{ printf "%s:6379,defaultDatabase=1,password=%s,connectTimeout=1000,abortConnect=false" .Values.externaldomain .Values.password | b64enc | quote }}
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}