apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthcheck-redis.fullname" . }}
  labels:
    {{- include "healthcheck-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "healthcheck-redis.selectorLabels" . | nindent 4 }}
