version: "3.4"

services:
  healthcheck-rabbitmq:
    image: mmercan/healthcheck-rabbitmq:${TAGVersion}-prod-linux
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      NAME: "rabbitmq1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    ports:
      - "15672:15672"
      - "5672:5672"
