apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: healthchecks.sentinel.mercan.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: sentinel.mercan.io
  names:
    plural: healthchecks
    singular: healthcheck
    kind: HealthCheck
    shortNames:
      - hc
      - health
  scope: Namespaced
  versions:
    - name: v1
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Service
          type: string
          jsonPath: .spec.service
        - name: Crontab
          type: string
          jsonPath: .spec.crontab
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          jsonPath: .status.phase
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object

            spec:
              type: object
              properties:
                service:
                  type: string
                crontab:
                  type: string
                isaliveUrl:
                  type: string
                isaliveandwellUrl:
                  type: string
                clientid:
                  type: string
                cert:
                  type: string
                replicas:
                  type: integer
              required:
                - service
                - crontab
            status:
              description: Status of the Certificate. This is set and managed automatically.
              type: object
              properties:
                lastCheckTime:
                  type: string
                lastFailureTime:
                  description: LastFailureTime is the time as recorded by the Certificate controller of the most recent failure to complete a CertificateRequest for this Certificate resource. If set, cert-manager will not re-request another Certificate until 1 hour has elapsed from this time.
                  type: string
                  format: date-time
                message:
                  type: string
                phase:
                  type: string
                  default: "Pending"
                replicas:
                  type: integer
                labelSelector:
                  type: string
      served: true
      storage: true
