apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-worker-healthchecker.name" . }}
  labels:
    {{- include "sentinel-worker-healthchecker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    {{- include "sentinel-worker-healthchecker.selectorLabels" . | nindent 4 }}
