name: Healthcheck_RabbitMQ

on:
  push:
    branches: [master]
    paths:
      - Containers/RabbitMQ/**
      - Helm/sentinel-healthcheck/charts/healthcheck-rabbitmq/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: View Docker Compose config
        run: |
          docker-compose --file Containers/RabbitMQ/docker-compose.yml --log-level DEBUG config

      - name: Build RabbitMQ Docker Image
        run: |
          docker-compose --file Containers/RabbitMQ/docker-compose.yml --log-level DEBUG build

      - name: tag Images
        run: |
          images=$(cat ./Containers/RabbitMQ/docker-compose.yml | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker tag "${image}":"01-prod-linux" "${image}":"$GITHUB_RUN_ID"
            docker tag "${image}":"01-prod-linux" "${image}":"latest"
          done

      - name: list Images
        run: |
          docker images

      - name: Push Images
        run: |
          images=$(cat ./Containers/RabbitMQ/docker-compose.yml | grep 'image: ' | cut -d':' -f 2 | tr -d '"')
          for image in $images 
          do 
            docker image push --all-tags ${image}
          done
  deploy-dev:
    environment: Dev
    needs: build
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      chartName: "healthcheck-rabbitmq"
      namespace: "sentinel-healthcheck"
      releaseName: "healthcheck-rabbitmq-dev"
      arecord: "rabbitmq-dev"
      pipelines_pipeline: '"${{ github.WORKFLOW }}"'

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: extract password
        run: |
          IP=$(curl "https://api.happi.dev/v1/generate-password?apikey=${{ secrets.HAPPI_APIKEY }}&limit=1&length=24&num=1&upper=1&symbols=0")
          password=$(jq -n "$IP" | jq .passwords[0] | tr -d '"')
          echo "::add-mask::$password"
          echo "RABBITMQ_PASSWORD=$(echo $password)" >> $GITHUB_ENV

      - name: Test
        run: echo $RABBITMQ_PASSWORD

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-aks

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config
          ls /home/runner/work/_temp

      - name: Check Helm Version
        run: |
          helm version

      - name: Helm Package
        run: |
          helm package --version 2.0.0-$GITHUB_RUN_ID --destination /home/runner/work/_temp ./Helm/sentinel-healthcheck/charts/$chartName

      - name: Validate Helm Package
        run: |
          helm template "./Helm/sentinel-healthcheck/charts/$chartName" -f "./Helm/values/$chartName/dev-values.yaml"

      - name: Helm upgrade
        run: |
          helm upgrade --namespace $namespace --install \
          --history-max 1 \
          --values ./Helm/values/$chartName/dev-values.yaml \
          --set image.tag=$GITHUB_RUN_ID \
          --set rabbitmq.password=$RABBITMQ_PASSWORD \
          --set branch=master \
          --wait $releaseName \
          /home/runner/work/_temp/$chartName-2.0.0-$GITHUB_RUN_ID.tgz \

      - name: extractExternalIP
        run: |
          sleep 10
          while [ -z $external_ip ]; do
          echo "Waiting for end point..."
          external_ip=$(kubectl get svc $releaseName -n $namespace --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")
          [ -z "$external_ip" ] && sleep 10
          done
          echo "EXTERNAL_IP=$(echo $external_ip)" >> $GITHUB_ENV
          echo "::add-mask::$external_ip"

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            if [ $(az network dns record-set list -g dnsmanagement -z  ${{ secrets.ENV_DOMAIN }}  --query "[?name=='$arecord']|  length(@)") = 0 ]; then
              echo $arecord" not found, create resource" 
              az network dns record-set a add-record -g dnsmanagement -z ${{ secrets.ENV_DOMAIN }} -n $arecord -a $EXTERNAL_IP
            else
              echo  $arecord "found, checking resource IP"
              oldIP=$(az network dns record-set list -g dnsmanagement -z myrcan.com  --query "[?name=='$arecord'] | [].aRecords[].ipv4Address | [0]")

              # remove first and last char
              oldIP="${oldIP:1:-1}"
              echo "::add-mask::$oldIP"

              echo $oldIP && echo $EXTERNAL_IP
              if [ "$oldIP" = "$EXTERNAL_IP" ]; then
               echo "Same IP no update"
              else
               echo "Different IP delete and create new"
                az network dns record-set a remove-record -g dnsmanagement -z ${{ secrets.ENV_DOMAIN }} -n $arecord --ipv4-address $oldIP 
                az network dns record-set a add-record -g dnsmanagement -z ${{ secrets.ENV_DOMAIN }} -n $arecord --ipv4-address $EXTERNAL_IP
              fi
            fi

      - name: output env vars
        run: |
          echo  " $ARTIFACT_PATH "
          echo  " $IMAGE_NAME "
          echo  " $chartName "
          echo  " $namespace "
          echo  " $releaseName "
          echo  " $pipelines_pipeline "
          echo  " $pipelines_run "
          echo  " $pipelines_org "
          echo  " $pipelines_repo "
          echo  " $pipelines_gitsha "
          echo  " $pipelines_branch "
          echo  " $pipelines_runuri "
