name: Healthcheck Redis

on:
  push:
    branches: [master]
    paths:
      - Containers/Redis/**
      - Helm/sentinel-healthcheck/charts/healthcheck-redis/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-test-aks2

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config
          ls /home/runner/work/_temp

      - name: View Docker Compose config
        run: |
          docker-compose --file ./Containers/Redis/docker-compose.yml --log-level DEBUG config

      - name: Build Redis Docker Image
        run: |
          docker-compose --file ./Containers/Redis/docker-compose.yml --log-level DEBUG build

      - name: tag Images
        run: |
          images=$(cat ./Containers/Redis/docker-compose.yml | grep 'image: ' | cut -d':' -f 2 | tr -d '"') \
          for image in $images \
          do \
            docker tag "${image}":"${{ env.GITHUB_RUN_ID }}" "${image}":latest \
          done
