name: Healthcheck Common Config

on:
  push:
    branches: [master]
    paths:
      - Helm/sentinel-healthcheck/charts/healthcheck-commonconfig/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      chartName: "healthcheck-commonconfig"
      namespace: "sentinel-healthcheck"
      releaseName: "sentinel-healthcheck-dev"
      BUILDTIME_ADID: "${{ secrets.BUILDTIME_ADID }}"
      BUILDTIME_APPID: "${{ secrets.BUILDTIME_APPID }}"
      BUILDTIME_APPSECRET: "${{ secrets.BUILDTIME_APPSECRET }}"
      pipelines_runuri: '"${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }}"'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-aks

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config
          ls /home/runner/work/_temp

      - name: Check Helm Version
        run: |
          helm version

      - name: Helm Package
        run: |
          helm package --version 2.0.0-$GITHUB_RUN_ID --destination /home/runner/work/_temp ./Helm/sentinel-healthcheck/charts/$chartName

      - name: Validate Helm Package
        run: |
          helm template "./Helm/sentinel-healthcheck/charts/$chartName" -f "./Helm/values/$chartName/dev-values.yaml"

      - name: Helm upgrade
        run: |
          helm upgrade --namespace $namespace --install \
          --history-max 1 \
          --values ./Helm/values/$chartName/dev-values.yaml \
          --set secrets.AzureAd__ClientId=$BUILDTIME_APPID \
          --set secrets.AzureAd__Secret=$BUILDTIME_APPSECRET \
          --set secrets.AzureAd__TenantId=$BUILDTIME_ADID \
          --set secrets.67d009b197fe496384ff3590b06df0da__ClientId=$BUILDTIME_APPID \
          --set secrets.67d009b197fe496384ff3590b06df0da__Secret=$BUILDTIME_APPSECRET \
          --set secrets.67d009b197fe496384ff3590b06df0da__TenantId=$BUILDTIME_ADID \
          --wait $releaseName \
          /home/runner/work/_temp/$chartName-2.0.0-$GITHUB_RUN_ID.tgz \

      - name: output env vars
        run: |
          echo  " $ARTIFACT_PATH "
          echo  " $IMAGE_NAME "
          echo  " $chartName "
          echo  " $namespace "
          echo  " $releaseName "

  deploy-test:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      chartName: "healthcheck-commonconfig"
      namespace: "sentinel-tester"
      releaseName: "healthcheck-commonconfig-test"
      BUILDTIME_ADID: "${{ secrets.BUILDTIME_ADID }}"
      BUILDTIME_APPID: "${{ secrets.BUILDTIME_APPID }}"
      BUILDTIME_APPSECRET: "${{ secrets.BUILDTIME_APPSECRET }}"
      pipelines_runuri: '"${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }}"'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-aks

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config
          ls /home/runner/work/_temp

      - name: Check Helm Version
        run: |
          helm version

      - name: Helm Package
        run: |
          helm package --version 2.0.0-$GITHUB_RUN_ID --destination /home/runner/work/_temp ./Helm/sentinel-healthcheck/charts/$chartName

      - name: Validate Helm Package
        run: |
          helm template "./Helm/sentinel-healthcheck/charts/$chartName" -f "./Helm/values/$chartName/dev-values.yaml"

      - name: Helm upgrade
        run: |
          helm upgrade --namespace $namespace --install \
          --history-max 1 \
          --values ./Helm/values/$chartName/dev-values.yaml \
          --set secrets.AzureAd__ClientId=$BUILDTIME_APPID \
          --set secrets.AzureAd__Secret=$BUILDTIME_APPSECRET \
          --set secrets.AzureAd__TenantId=$BUILDTIME_ADID \
          --wait $releaseName \
          /home/runner/work/_temp/$chartName-2.0.0-$GITHUB_RUN_ID.tgz \

      - name: output env vars
        run: |
          echo  " $ARTIFACT_PATH "
          echo  " $IMAGE_NAME "
          echo  " $chartName "
          echo  " $namespace "
          echo  " $releaseName "
