name: Sentinel Test Direct

on:
  push:
    branches: ["*"]
    paths:
      - Workers/**
      - Libs/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      APPID: ${{ secrets.buildtime_APPID }}
      APPSECRET: ${{ secrets.buildtime_APPSECRET }}
      ADID: ${{ secrets.buildtime_ADID }}
      SONARKEY: ${{ secrets.buildtime_SONARKEY }}
      RabbitMQConnection: ${{ secrets.RABBITMQCONNECTION }}
      Mongodb__ConnectionString: ${{ secrets.MONGODB__CONNECTIONSTRING }}
      RedisConnection: ${{ secrets.REDISCONNECTION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-aks

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config
          ls /home/runner/work/_temp

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test
        env:
          RabbitMQConnection: ${{ secrets.RABBITMQCONNECTION }}
          Mongodb__ConnectionString: ${{ secrets.MONGODB__CONNECTIONSTRING }}
          RedisConnection: ${{ secrets.REDISCONNECTION }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults
